# Generated by Django 4.2.16 on 2024-10-23 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamestore', '0004_alter_game_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='Наличие'),
        ),
    ]
